// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TiendaServicios.Api.Libreria.Context;

namespace TiendaServicios.Api.Libreria.Migrations
{
    [DbContext(typeof(ContextoLibro))]
    partial class ContextoLibroModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TiendaServicios.Api.Libreria.Entities.Libros", b =>
                {
                    b.Property<int>("LibrosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AutorLibro")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LibroGuid")
                        .HasColumnType("text");

                    b.Property<string>("TituloLibro")
                        .HasColumnType("text");

                    b.HasKey("LibrosId");

                    b.ToTable("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
